/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/DisplayMenus.ts
var import_obsidian = require("obsidian");
function createCodingsMenu(plugin) {
  createRibbonButtons(plugin);
  createCommands(plugin);
}
function createRibbonButtons(plugin) {
  Object.values(plugin.menuOptions).forEach((option) => {
    plugin.addRibbonIcon(option.icon, option.title, () => option.action(plugin));
  });
}
function createCommands(plugin) {
  Object.values(plugin.menuOptions).forEach((option) => {
    plugin.addCommand({
      id: option.title.toLowerCase().replace(/ /g, "-"),
      name: option.title,
      callback: () => option.action(plugin)
    });
  });
}
function createFileMenu(menu, file, plugin) {
  createDefaultObsidianMenus(menu, plugin);
}
function createEditorMenu(menu, plugin) {
  createDefaultObsidianMenus(menu, plugin);
}
async function createEditorCodingMenu(editor, evt, plugin) {
  const selectedText = editor.getSelection();
  if (selectedText && !plugin.selectionTriggeredMenu) {
    plugin.selectionTriggeredMenu = true;
    if (plugin.currentMenu) {
      plugin.currentMenu.hide();
    }
    const submenu = new import_obsidian.Menu();
    Object.values(plugin.menuOptions).forEach((option) => {
      if (option.isToggle) {
        submenu.addItem((item) => {
          var _a;
          const toggleComponent = new import_obsidian.ToggleComponent(item.dom);
          toggleComponent.setValue((_a = option.isEnabled) != null ? _a : false);
          toggleComponent.onChange((value) => {
            option.isEnabled = value;
            option.action(plugin);
            plugin.selectionTriggeredMenu = true;
          });
          item.setTitle(option.title).setIcon(option.icon);
          item.dom.classList.add("menu-item-toggle");
          item.dom.addEventListener("click", (evt2) => {
            evt2.stopPropagation();
            const currentValue = toggleComponent.getValue();
            toggleComponent.setValue(!currentValue);
          });
        });
      } else if (option.isTextField) {
        submenu.addItem((item) => {
          const textComponent = new import_obsidian.TextComponent(item.dom);
          textComponent.setPlaceholder("Enter text...");
          textComponent.onChange((value) => {
            new import_obsidian.Notice(`Entered text: ${value}`);
            option.action(plugin);
          });
          item.setTitle(option.title).setIcon(option.icon);
          item.dom.classList.add("menu-item-textfield");
          item.dom.addEventListener("click", (evt2) => {
            evt2.stopPropagation();
            textComponent.inputEl.focus();
          });
          const handleEnterKey = (evt2) => {
            if (evt2.key === "Enter") {
              evt2.preventDefault();
              evt2.stopPropagation();
              addItemToEditorCodingMenu(textComponent.inputEl.value, plugin, editor, submenu);
              textComponent.inputEl.value = "";
              textComponent.inputEl.focus();
            }
          };
          window.addEventListener("keydown", handleEnterKey, true);
          textComponent.inputEl.addEventListener("keydown", handleEnterKey, true);
          submenu.onHide(() => {
            window.removeEventListener("keydown", handleEnterKey, true);
            textComponent.inputEl.removeEventListener("keydown", handleEnterKey, true);
            plugin.selectionTriggeredMenu = false;
          });
        });
      } else {
        submenu.addItem((item) => {
          item.setTitle(option.title).setIcon(option.icon).onClick(() => {
            option.action(plugin);
            resetMenu(plugin);
          });
        });
      }
    });
    submenu.onHide(() => {
      if (!plugin.selectionTriggeredMenu) {
        plugin.selectionTriggeredMenu = false;
      }
    });
    submenu.showAtPosition({ x: evt.pageX, y: evt.pageY });
    plugin.currentMenu = submenu;
  }
}
function addItemToEditorCodingMenu(value, plugin, editor, submenu) {
  if (value.trim() !== "") {
    new import_obsidian.Notice(`Text added to editor: ${value}`);
    const newOption = {
      title: value,
      icon: "tag",
      action: (plugin2) => {
        new import_obsidian.Notice(`Toggle ${value} executed`);
      },
      isToggle: true,
      isEnabled: false
    };
    plugin.menuOptions.push(newOption);
    submenu.addItem((item) => {
      var _a;
      const toggleComponent = new import_obsidian.ToggleComponent(item.dom);
      toggleComponent.setValue((_a = newOption.isEnabled) != null ? _a : false);
      toggleComponent.onChange((toggleValue) => {
        newOption.isEnabled = toggleValue;
        newOption.action(plugin);
      });
      item.setTitle(newOption.title).setIcon(newOption.icon);
      item.dom.classList.add("menu-item-toggle");
      item.dom.addEventListener("click", (evt) => {
        evt.stopPropagation();
        const currentValue = toggleComponent.getValue();
        toggleComponent.setValue(!currentValue);
      });
    });
    submenu.hide();
    submenu.showAtPosition({ x: submenu.posX, y: submenu.posY });
  }
}
function resetMenu(plugin, hideMenu = true) {
  if (plugin.currentMenu) {
    plugin.currentMenu.hide();
    plugin.currentMenu = null;
  }
  plugin.selectionTriggeredMenu = false;
  plugin.contextMenuOpened = false;
}
function createDefaultObsidianMenus(menu, plugin) {
  menu.addSeparator();
  menu.addItem((item) => {
    item.setTitle("Code Options").setIcon("dice");
    const submenu = item.setSubmenu();
    Object.values(plugin.menuOptions).forEach((option) => {
      submenu.addItem((subItem) => {
        subItem.setTitle(option.title).setIcon(option.icon).onClick(() => option.action(plugin));
      });
    });
  });
}
function toggleExample(plugin) {
  const toggleOption = plugin.menuOptions.find((option) => option.title === "Toggle Example");
  if (toggleOption) {
    new import_obsidian.Notice(`Toggle is now ${toggleOption.isEnabled ? "enabled" : "disabled"}`);
  }
}

// src/Events.ts
var import_obsidian3 = require("obsidian");

// src/CodingModals.ts
var import_obsidian2 = require("obsidian");
var ApplyCodeModal = class extends import_obsidian2.Modal {
  constructor(app2, editor) {
    super(app2);
    this.editor = editor;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Apply Code" });
    const codeInput = contentEl.createEl("input", { type: "text", placeholder: "Enter code" });
    const colorInput = contentEl.createEl("input", { type: "color", value: "#ffff00" });
    const applyButton = contentEl.createEl("button", { text: "Apply" });
    applyButton.onclick = () => {
      this.code = codeInput.value.trim();
      const color = colorInput.value;
      if (this.code) {
        this.applyCodeToSelection(this.code, color);
      }
      this.close();
    };
  }
  applyCodeToSelection(code, color) {
    const selection = this.editor.getSelection();
    const codedText = `<span class="coded-text ${sanitizeCodeName(code)}" data-code="${code}">${selection}</span>`;
    this.editor.replaceSelection(codedText);
    saveCodeData(this.editor.getDoc().getValue());
    addDynamicStyle(code, color);
    storeStyle(code, color);
  }
  /*
  	saveCodeData(content: string) {
  		new Notice("saveCodeData")
  		const filePath = this.app.workspace.getActiveFile()?.path;
  		if (filePath) {
  			const codeData = { path: filePath, content: content };
  			localStorage.setItem('codeData', JSON.stringify(codeData));
  		}
  	}
  	
  	addDynamicStyle(code: string, color: string) {
  		const styleId = `style-${this.sanitizeCodeName(code)}`;
  		let style = document.getElementById(styleId);
  
  		if (!style) {
  			style = document.createElement('style');
  			style.id = styleId;
  			document.head.appendChild(style);
  		}
  
  		style.innerHTML = `.coded-text.${this.sanitizeCodeName(code)} { background-color: ${color}; }`;
  	}
  */
  /* sanitizeCodeName(code: string): string {
  	return code.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  } */
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  /* getActiveEditor(): Editor | null {
  	const activeLeaf = this.app.workspace.activeLeaf;
  	if (activeLeaf) {
  		const view = activeLeaf.view as MarkdownView;
  		return view.editor;
  	}
  	return null;
  } */
};
var RemoveCodeModal = class extends import_obsidian2.Modal {
  constructor(app2, editor) {
    super(app2);
    this.editor = editor;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Remove Code" });
    const removeButton = contentEl.createEl("button", { text: "Remove" });
    removeButton.onclick = () => {
      this.removeCodeFromSelection();
      this.close();
    };
  }
  removeCodeFromSelection() {
    const selection = this.editor.getSelection();
    const cleanedText = selection.replace(/<span\b[^>]*?\bclass="[^"]*\bcoded-text\b[^"]*"[^>]*?>(.*?)<\/span>/gis, "$1");
    this.editor.replaceSelection(cleanedText);
    saveCodeData(this.editor.getDoc().getValue());
    this.removeDynamicStyle(cleanedText);
  }
  /* saveCodeData(content: string) {
  	const filePath = this.app.workspace.getActiveFile()?.path;
  	if (filePath) {
  		const codeData = { path: filePath, content: content };
  		localStorage.setItem('codeData', JSON.stringify(codeData));
  	}
  } */
  removeDynamicStyle(code) {
    const styleId = `style-${sanitizeCodeName(code)}`;
    const style = document.getElementById(styleId);
    if (style) {
      style.remove();
    }
  }
  /* sanitizeCodeName(code: string): string {
  	return code.replace(/[^a-z0-9]/gi, '-').toLowerCase();
  } */
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
function cleanAllCodes(editor) {
  const content = editor.getValue();
  const cleanedContent = content.replace(/<span\b[^>]*?\bclass="[^"]*\bcoded-text\b[^"]*"[^>]*?>(.*?)<\/span>/gis, "$1");
  editor.setValue(cleanedContent);
  localStorage.removeItem("dynamicStyles");
}
function getActiveEditor() {
  const activeLeaf = this.app.workspace.activeLeaf;
  if (activeLeaf) {
    const view = activeLeaf.view;
    if (view instanceof import_obsidian2.MarkdownView) {
      return view.editor;
    }
  }
  return null;
}
function saveCodeData(content) {
  var _a;
  const filePath = (_a = app.workspace.getActiveFile()) == null ? void 0 : _a.path;
  if (filePath) {
    const codeData = { path: filePath, content };
    localStorage.setItem("codeData", JSON.stringify(codeData));
  }
}
function loadCodeData() {
  var _a;
  const filePath = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path;
  const codeData = localStorage.getItem("codeData");
  if (filePath && codeData) {
    const parsedCodeData = JSON.parse(codeData);
    if (parsedCodeData.path === filePath) {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        this.app.vault.modify(activeFile, parsedCodeData.content);
      }
    }
  }
}
function reapplyStyles() {
  const styles = JSON.parse(localStorage.getItem("dynamicStyles") || "{}");
  for (const [code, color] of Object.entries(styles)) {
    addDynamicStyle(code, color);
  }
}
function addDynamicStyle(code, color) {
  const styleId = `style-${sanitizeCodeName(code)}`;
  let style = document.getElementById(styleId);
  if (!style) {
    style = document.createElement("style");
    style.id = styleId;
    document.head.appendChild(style);
  }
  style.innerHTML = `.coded-text.${sanitizeCodeName(code)} { background-color: ${color}; }`;
}
function storeStyle(code, color) {
  const styles = JSON.parse(localStorage.getItem("dynamicStyles") || "{}");
  styles[code] = color;
  localStorage.setItem("dynamicStyles", JSON.stringify(styles));
}
function sanitizeCodeName(code) {
  return code.replace(/[^a-z0-9]/gi, "-").toLowerCase();
}

// src/Events.ts
function createRegisterEvents(plugin) {
  plugin.registerEvent(plugin.app.workspace.on("editor-menu", (menu, editor) => {
    createEditorMenu(menu, plugin);
  }));
  plugin.registerEvent(plugin.app.workspace.on("file-menu", async (menu, file) => {
    if (file instanceof import_obsidian3.TFile) {
      createFileMenu(menu, file, plugin);
    }
  }));
  plugin.registerDomEvent(document, "contextmenu", (evt) => {
    const activeLeaf = plugin.app.workspace.activeLeaf;
    if (!((activeLeaf == null ? void 0 : activeLeaf.view) instanceof import_obsidian3.MarkdownView)) {
      return;
    }
    plugin.contextMenuOpened = true;
  });
  plugin.registerEvent(this.app.workspace.on("file-open", () => {
    loadCodeData();
    reapplyStyles();
  }));
  plugin.registerDomEvent(document, "DOMContentLoaded", () => {
    const link = document.createElement("link");
    link.rel = "stylesheet";
    link.href = "styles.css";
    document.head.appendChild(link);
    reapplyStyles();
  });
  addMouseUpEvent(plugin);
}
function addMouseUpEvent(plugin) {
  plugin.registerDomEvent(
    document,
    "mouseup",
    async (evt) => {
      if (!plugin.selectionTriggeredMenu) {
        console.log("padr\xE3o");
        resetMenu(plugin);
      }
      const activeLeaf = this.app.workspace.activeLeaf;
      if (!((activeLeaf == null ? void 0 : activeLeaf.view) instanceof import_obsidian3.MarkdownView)) {
        return;
      }
      const editor = activeLeaf.view.editor;
      if (!editor.hasFocus()) {
        return;
      }
      if (evt.button === 2) {
        this.selectionTriggeredMenu = true;
        this.contextMenuOpened = true;
        this.codingMenuOpened = false;
        return;
      }
      if (this.contextMenuOpened) {
        resetMenu(plugin);
        this.contextMenuOpened = false;
        this.codingMenuOpened = true;
        return;
      }
      const selectedText = editor.getSelection();
      if (selectedText === " ") {
        this.contextMenuOpened = false;
        this.codingMenuOpened = false;
        return;
      }
      if (!this.codingMenuOpened && !this.contextMenuOpened) {
        await createEditorCodingMenu(editor, evt, plugin);
      } else if (this.codingMenuOpened) {
        resetMenu(plugin);
        this.codingMenuOpened = false;
        return;
      }
    }
  );
}

// src/Coding.ts
var import_obsidian4 = require("obsidian");
function addNewCode(plugin) {
  const editor = getActiveEditor();
  if (editor) {
    new ApplyCodeModal(plugin.app, editor).open();
  }
  resetMenu(this);
}
function addExistingCode(plugin) {
  new import_obsidian4.Notice("Add Existing Code");
  resetMenu(this);
}
function removeCode(plugin) {
  new import_obsidian4.Notice("Remove Code");
  const editor = getActiveEditor();
  if (editor) {
    new RemoveCodeModal(plugin.app, editor).open();
  }
  resetMenu(this);
}
function removeAllCodes(plugin) {
  new import_obsidian4.Notice("Remove Code");
  const editor = getActiveEditor();
  if (editor) {
    cleanAllCodes(editor);
  }
  resetMenu(this);
}

// main.ts
var MyPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.currentMenu = null;
    this.menuOptions = [
      { title: "Add New Code", icon: "plus", action: (plugin) => addNewCode(plugin) },
      { title: "Add Existing Code", icon: "check", action: (plugin) => addExistingCode(plugin) },
      { title: "Remove Code", icon: "trash", action: (plugin) => removeCode(plugin) },
      { title: "Remove All Codes", icon: "x", action: (plugin) => removeAllCodes(plugin) },
      { title: "Toggle Example", icon: "toggle-left", action: (plugin) => toggleExample(plugin), isToggle: true, isEnabled: false },
      { title: "New Item", icon: "pencil", action: () => {
      }, isTextField: true }
    ];
    this.selectionTriggeredMenu = false;
    this.contextMenuOpened = false;
  }
  async onload() {
    console.log("[menu-editors] v9 loaded -- Clique milestone: click post create item funcionando");
    createRegisterEvents(this);
    createCodingsMenu(this);
  }
  onunload() {
    new import_obsidian5.Notice("Plugin unloaded");
  }
};
