import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync } from "fs";
import { resolve } from "path";

const DEMO_PLUGIN_DIR = "demo/.obsidian/plugins/obsidian-codemarker-v2";

const copyToDemo = {
	name: "copy-to-demo",
	setup(build) {
		build.onEnd(() => {
			const dest = resolve(DEMO_PLUGIN_DIR);
			mkdirSync(dest, { recursive: true });
			for (const f of ["main.js", "manifest.json", "styles.css"]) {
				try { copyFileSync(f, resolve(dest, f)); } catch {}
			}
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToDemo],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
