import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { copyFileSync, mkdirSync } from "fs";

const DEMO_PLUGIN_DIR = "demo/.obsidian/plugins/obsidian-codemarker";

const copyToDemo = {
	name: "copy-to-demo",
	setup(build) {
		build.onEnd(() => {
			try {
				mkdirSync(DEMO_PLUGIN_DIR, { recursive: true });
				copyFileSync("main.js", `${DEMO_PLUGIN_DIR}/main.js`);
				copyFileSync("manifest.json", `${DEMO_PLUGIN_DIR}/manifest.json`);
				copyFileSync("styles.css", `${DEMO_PLUGIN_DIR}/styles.css`);
				console.log("Copied to demo vault");
			} catch (e) {
				console.warn("Copy to demo failed:", e.message);
			}
		});
	}
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
	plugins: [copyToDemo],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
