/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => QualitativeCodingPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var ApplyCodeModal = class extends import_obsidian.Modal {
  constructor(app, editor) {
    super(app);
    this.editor = editor;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Apply Code" });
    const codeInput = contentEl.createEl("input", { type: "text", placeholder: "Enter code" });
    const colorInput = contentEl.createEl("input", { type: "color", value: "#ffff00" });
    const applyButton = contentEl.createEl("button", { text: "Apply" });
    applyButton.onclick = () => {
      this.code = codeInput.value.trim();
      const color = colorInput.value;
      if (this.code) {
        this.applyCodeToSelection(this.code, color);
      }
      this.close();
    };
  }
  applyCodeToSelection(code, color) {
    const selection = this.editor.getSelection();
    const codedText = `<span class="coded-text ${this.sanitizeCodeName(code)}" data-code="${code}" data-color="${color}">${selection}</span>`;
    this.editor.replaceSelection(codedText);
    this.saveCodeData(this.editor.getDoc().getValue());
    this.addDynamicStyle(code, color);
  }
  saveCodeData(content) {
    var _a;
    const filePath = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path;
    if (filePath) {
      const codeData = { path: filePath, content };
      localStorage.setItem("codeData", JSON.stringify(codeData));
    }
  }
  addDynamicStyle(code, color) {
    const styleId = `style-${this.sanitizeCodeName(code)}`;
    let style = document.getElementById(styleId);
    if (!style) {
      style = document.createElement("style");
      style.id = styleId;
      document.head.appendChild(style);
    }
    style.innerHTML = `.coded-text.${this.sanitizeCodeName(code)} { background-color: ${color}; }`;
  }
  sanitizeCodeName(code) {
    return code.replace(/[^a-z0-9]/gi, "-").toLowerCase();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var RemoveCodeModal = class extends import_obsidian.Modal {
  constructor(app, editor) {
    super(app);
    this.editor = editor;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Remove Code" });
    const removeButton = contentEl.createEl("button", { text: "Remove" });
    removeButton.onclick = () => {
      this.removeCodeFromSelection();
      this.close();
    };
  }
  removeCodeFromSelection() {
    const selection = this.editor.getSelection();
    const cleanedText = selection.replace(/<span\b[^>]*?\bclass="[^"]*\bcoded-text\b[^"]*"[^>]*?>(.*?)<\/span>/gis, "$1");
    this.editor.replaceSelection(cleanedText);
    this.saveCodeData(this.editor.getDoc().getValue());
    this.removeDynamicStyle(cleanedText);
  }
  saveCodeData(content) {
    var _a;
    const filePath = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path;
    if (filePath) {
      const codeData = { path: filePath, content };
      localStorage.setItem("codeData", JSON.stringify(codeData));
    }
  }
  removeDynamicStyle(code) {
    const styleId = `style-${this.sanitizeCodeName(code)}`;
    const style = document.getElementById(styleId);
    if (style) {
      style.remove();
    }
  }
  sanitizeCodeName(code) {
    return code.replace(/[^a-z0-9]/gi, "-").toLowerCase();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var CodeTooltip = class {
  constructor() {
    this.element = document.createElement("div");
    this.element.className = "code-tooltip";
    this.element.innerHTML = `
			<div class="tooltip-content">
				<span class="color-circle"></span>
				<span class="code-name"></span>
				<button class="remove-code">x</button>
			</div>
		`;
    document.body.appendChild(this.element);
    const removeButton = this.element.querySelector(".remove-code");
    if (removeButton) {
      removeButton.addEventListener("click", () => {
        this.removeCode();
      });
    }
  }
  show(target, code, color) {
    const rect = target.getBoundingClientRect();
    this.element.style.top = `${rect.top - 30}px`;
    this.element.style.left = `${rect.left}px`;
    const colorCircle = this.element.querySelector(".color-circle");
    if (colorCircle) {
      colorCircle.style.backgroundColor = color;
    }
    const codeNameElement = this.element.querySelector(".code-name");
    if (codeNameElement) {
      codeNameElement.textContent = code;
    }
    this.element.style.display = "block";
  }
  hide() {
    this.element.style.display = "none";
  }
  removeCode() {
    const selection = window.getSelection();
    if (selection && selection.rangeCount > 0) {
      const range = selection.getRangeAt(0);
      const span = range.commonAncestorContainer.parentElement;
      if (span && span.classList.contains("coded-text")) {
        const cleanedText = span.innerHTML;
        span.outerHTML = cleanedText;
      }
    }
    this.hide();
  }
};
var QualitativeCodingPlugin = class extends import_obsidian.Plugin {
  async onload() {
    console.log("[qualitative-coding-plugin] v1 loaded \u2014 ApplyCodeModal + highlight com cor");
    this.tooltip = new CodeTooltip();
    this.addCommand({
      id: "apply-code",
      name: "Apply Code to Selected Text",
      editorCallback: (editor, view) => {
        new ApplyCodeModal(this.app, editor).open();
      }
    });
    this.addCommand({
      id: "remove-code",
      name: "Remove Code from Selected Text",
      editorCallback: (editor, view) => {
        new RemoveCodeModal(this.app, editor).open();
      }
    });
    this.addRibbonIcon("sun", "Apply Code", (evt) => {
      const editor = this.getActiveEditor();
      if (editor) {
        new ApplyCodeModal(this.app, editor).open();
      }
    });
    this.addRibbonIcon("cross", "Remove Code", (evt) => {
      const editor = this.getActiveEditor();
      if (editor) {
        new RemoveCodeModal(this.app, editor).open();
      }
    });
    this.registerEvent(this.app.workspace.on("file-menu", (menu, file) => {
      this.addContextMenuItems(menu);
    }));
    this.registerDomEvent(document, "DOMContentLoaded", () => {
      const link = document.createElement("link");
      link.rel = "stylesheet";
      link.href = "styles.css";
      document.head.appendChild(link);
    });
    this.registerDomEvent(document, "mouseover", (evt) => {
      const target = evt.target;
      if (target && target.classList.contains("coded-text")) {
        const code = target.getAttribute("data-code");
        const color = target.getAttribute("data-color");
        if (code && color) {
          this.tooltip.show(target, code, color);
        }
      }
    });
    this.registerDomEvent(document, "mouseout", (evt) => {
      const target = evt.target;
      if (target && target.classList.contains("coded-text")) {
        this.tooltip.hide();
      }
    });
    this.registerEvent(this.app.workspace.on("file-open", () => {
      this.loadCodeData();
    }));
  }
  onunload() {
    console.log("Unloading qualitative coding plugin");
  }
  getActiveEditor() {
    const activeLeaf = this.app.workspace.activeLeaf;
    if (activeLeaf) {
      const view = activeLeaf.view;
      return view.editor;
    }
    return null;
  }
  addContextMenuItems(menu) {
    menu.addSeparator();
    menu.addItem((item) => {
      item.setTitle("Qualitative Coding").setIcon("pencil");
    });
    menu.addItem((item) => {
      item.setTitle("Apply Code").setIcon("highlight").onClick(() => {
        const editor = this.getActiveEditor();
        if (editor) {
          new ApplyCodeModal(this.app, editor).open();
        }
      });
    });
    menu.addItem((item) => {
      item.setTitle("Remove Code").setIcon("cross").onClick(() => {
        const editor = this.getActiveEditor();
        if (editor) {
          new RemoveCodeModal(this.app, editor).open();
        }
      });
    });
    menu.addSeparator();
  }
  loadCodeData() {
    var _a;
    const filePath = (_a = this.app.workspace.getActiveFile()) == null ? void 0 : _a.path;
    const codeData = localStorage.getItem("codeData");
    if (filePath && codeData) {
      const parsedCodeData = JSON.parse(codeData);
      if (parsedCodeData.path === filePath) {
        const activeFile = this.app.workspace.getActiveFile();
        if (activeFile) {
          this.app.vault.modify(activeFile, parsedCodeData.content);
        }
      }
    }
  }
};
