/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_promises = require("fs/promises");
var path = __toESM(require("path"));
var VIEW_TYPE_CSV = "csv-view";
var MyPlugin = class extends import_obsidian.Plugin {
  async onload() {
    var _a;
    console.log("[Management Codes] v12 loaded -- Code management: CSV view + file operations");
    this.addRibbonIcon("file-plus", "Add Item", async () => {
      new InputModal(this).open();
    });
    this.registerView(
      VIEW_TYPE_CSV,
      (leaf) => new CSVView(leaf, this)
    );
    if (!this.app.workspace.getLeavesOfType(VIEW_TYPE_CSV).length) {
      (_a = this.app.workspace.getRightLeaf(false)) == null ? void 0 : _a.setViewState({
        type: VIEW_TYPE_CSV
      });
    }
  }
  async saveItemToCSV(item) {
    const filePath = this.getCSVFilePath();
    try {
      await this.ensureFileExists(filePath);
      await (0, import_promises.appendFile)(filePath, `${item}
`);
      new import_obsidian.Notice("Item added to CSV");
      this.updateCSVView();
    } catch (error) {
      console.error("Failed to save item to CSV:", error);
      new import_obsidian.Notice("Failed to save item to CSV");
    }
  }
  getCSVFilePath() {
    const basePath = this.app.vault.adapter.basePath || this.app.vault.configDir;
    return path.join(basePath, "items.csv");
  }
  async ensureFileExists(filePath) {
    try {
      await (0, import_promises.access)(filePath, import_promises.constants.F_OK);
    } catch (error) {
      await (0, import_promises.writeFile)(filePath, "");
    }
  }
  async updateCSVView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE_CSV);
    if (leaves.length) {
      const view = leaves[0].view;
      view.loadItemsFromCSV();
    }
  }
};
var CSVView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
    this.loadItemsFromCSV();
  }
  getViewType() {
    return VIEW_TYPE_CSV;
  }
  getDisplayText() {
    return "CSV Items";
  }
  async loadItemsFromCSV() {
    const filePath = this.plugin.getCSVFilePath();
    let content = "";
    try {
      await this.plugin.ensureFileExists(filePath);
      content = await (0, import_promises.readFile)(filePath, "utf-8");
    } catch (error) {
      console.error("Failed to read CSV file:", error);
      new import_obsidian.Notice("Failed to load CSV items");
    }
    const items = content.split("\n").filter((line) => line.trim() !== "");
    const container = this.containerEl.children[1];
    container.empty();
    items.forEach((item) => {
      const div = document.createElement("div");
      div.textContent = item;
      container.appendChild(div);
    });
  }
  async onOpen() {
    this.loadItemsFromCSV();
  }
  async onClose() {
  }
};
var InputModal = class extends import_obsidian.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Add New Item" });
    this.input = new import_obsidian.TextComponent(contentEl);
    this.input.inputEl.style.width = "100%";
    this.input.inputEl.focus();
    const saveButton = contentEl.createEl("button", { text: "Save" });
    saveButton.style.marginTop = "10px";
    saveButton.onclick = async () => {
      const newItem = this.input.getValue();
      if (newItem) {
        await this.plugin.saveItemToCSV(newItem);
        this.close();
      } else {
        new import_obsidian.Notice("Please enter a valid item");
      }
    };
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
