/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MyPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian8 = require("obsidian");

// src/backup/DisplayMenu.ts
var import_obsidian = require("obsidian");
var _CodingMenuManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  static async createEditorCodingMenu(editor, evt, plugin) {
    const submenu = new import_obsidian.Menu();
    const selectedText = editor.getSelection();
    const myCustomMenu = plugin.menuOptions;
    Object.values(myCustomMenu).forEach((option) => {
      if (option.isToggle) {
        submenu.addItem((item) => {
          var _a;
          const toggleComponent = new import_obsidian.ToggleComponent(item.dom);
          toggleComponent.setValue((_a = option.isEnabled) != null ? _a : false);
          toggleComponent.onChange((value) => {
            option.isEnabled = value;
            option.action(plugin);
          });
          item.setTitle(option.title).setIcon(option.icon);
          item.dom.classList.add("menu-item-toggle");
          item.dom.addEventListener("click", (evt2) => {
            evt2.stopPropagation();
            const currentValue = toggleComponent.getValue();
            toggleComponent.setValue(!currentValue);
          });
        });
      } else if (option.isTextField) {
        submenu.addItem((item) => {
          const textComponent = new import_obsidian.TextComponent(item.dom);
          textComponent.setPlaceholder("Enter text...");
          textComponent.onChange((value) => {
            option.action(plugin);
          });
          item.setTitle(option.title).setIcon(option.icon);
          item.dom.classList.add("menu-item-textfield");
          item.dom.addEventListener("click", (evt2) => {
            evt2.stopPropagation();
            evt2.preventDefault();
            textComponent.inputEl.focus();
          });
          const handleEnterKey = (evt2) => {
            if (evt2.key === "Enter") {
              evt2.stopPropagation();
              evt2.preventDefault();
              if (_CodingMenuManager.lastMouseEvent) {
                this.cleanupCallbacks.forEach((callback) => callback());
                _CodingMenuManager.addItemToEditorCodingMenu(textComponent.inputEl.value, plugin, editor, submenu, _CodingMenuManager.lastMouseEvent);
              }
            }
          };
          this.cleanupCallbacks.push(() => {
            window.removeEventListener("keydown", handleEnterKey, true);
          });
          this.focusCallbacks.push(() => {
            textComponent.inputEl.focus();
          });
          window.addEventListener("keydown", handleEnterKey, true);
        });
      } else {
        submenu.addItem((item) => {
          item.setTitle(option.title).setIcon(option.icon).onClick(() => {
            option.action(plugin);
            _CodingMenuManager.resetMenu(plugin);
          });
        });
      }
    });
    submenu.onHide(async () => {
      plugin.codingMenuOpened = false;
      plugin.menuStayOpen = true;
      this.resetMenu(plugin);
    });
    plugin.codingMenuOpened = true;
    submenu.showAtPosition({ x: evt.pageX, y: evt.pageY });
    this.focusCallbacks.forEach((callback) => callback());
    this.focusCallbacks = [];
    _CodingMenuManager.lastMouseEvent = evt;
    plugin.currentMenu = submenu;
  }
  static addItemToEditorCodingMenu(value, plugin, editor, submenu, originalEvent) {
    if (value.trim() !== "") {
      const newOption = {
        title: value,
        icon: "tag",
        action: (plugin2) => {
          new import_obsidian.Notice(`Toggle ${value} executed`);
        },
        isToggle: true,
        isEnabled: true
      };
      plugin.menuOptions.push(newOption);
      submenu.hide();
      this.createEditorCodingMenu(editor, originalEvent, plugin);
      plugin.codingMenuOpened = true;
    }
  }
  static async resetMenu(plugin, hideMenu = true) {
    if (plugin.currentMenu) {
      plugin.currentMenu.hide();
      this.destroyMenu(plugin.currentMenu);
      plugin.currentMenu = null;
    }
    plugin.codingMenuOpened = false;
    plugin.menuStayOpen = false;
  }
  static destroyMenu(menu) {
    if (menu && menu.dom) {
      const menuDom = menu.dom;
      if (menuDom.parentNode) {
        menuDom.parentNode.removeChild(menuDom);
      }
    }
  }
};
var CodingMenuManager = _CodingMenuManager;
CodingMenuManager.handleEnterKey = null;
CodingMenuManager.lastMouseEvent = null;
CodingMenuManager.cleanupCallbacks = [];
CodingMenuManager.focusCallbacks = [];

// src/standardMenus.ts
var import_obsidian2 = require("obsidian");
var StandardMenus = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  createMenus() {
    this.createRibbonButtons();
    this.createCommands();
    this.createEditorMenu();
    this.createFileMenu();
  }
  createRibbonButtons() {
    Object.values(this.plugin.menuOptions).forEach((option) => {
      this.plugin.addRibbonIcon(option.icon, option.title, () => option.action(this.plugin));
    });
  }
  createCommands() {
    Object.values(this.plugin.menuOptions).forEach((option) => {
      this.plugin.addCommand({
        id: option.title.toLowerCase().replace(/ /g, "-"),
        name: option.title,
        callback: () => option.action(this.plugin)
      });
    });
  }
  createEditorMenu() {
    this.plugin.registerEvent(this.plugin.app.workspace.on("editor-menu", (menu, editor) => {
      StandardMenus.createDefaultObsidianMenus(menu, this.plugin);
    }));
  }
  createFileMenu() {
    this.plugin.registerEvent(this.plugin.app.workspace.on("file-menu", async (menu, file) => {
      if (file instanceof import_obsidian2.TFile) {
        StandardMenus.createDefaultObsidianMenus(menu, this.plugin);
      }
    }));
    this.plugin.registerDomEvent(document, "contextmenu", (evt) => {
      const activeLeaf = this.plugin.app.workspace.activeLeaf;
      if (!((activeLeaf == null ? void 0 : activeLeaf.view) instanceof import_obsidian2.MarkdownView)) {
        return;
      }
      this.plugin.contextMenuOpened = true;
    });
  }
  static createDefaultObsidianMenus(menu, plugin) {
    menu.addSeparator();
    const submenu = new import_obsidian2.Menu();
    Object.values(plugin.menuOptions).forEach((option) => {
      submenu.addItem((subItem) => {
        subItem.setTitle(option.title).setIcon(option.icon).onClick(() => option.action(plugin));
      });
    });
    menu.addItem((item) => {
      item.setTitle("Code Options").setIcon("dice").onClick(() => submenu.showAtPosition({ x: item.dom.getBoundingClientRect().right, y: item.dom.getBoundingClientRect().top }));
    });
  }
};

// src/Events.ts
var import_obsidian6 = require("obsidian");

// src/CodingModals.ts
var import_obsidian3 = require("obsidian");
var ApplyCodeModal = class extends import_obsidian3.Modal {
  constructor(app2, editor) {
    super(app2);
    this.editor = editor;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Apply Code" });
    const codeInput = contentEl.createEl("input", { type: "text", placeholder: "Enter code" });
    const colorInput = contentEl.createEl("input", { type: "color", value: "#ffff00" });
    const applyButton = contentEl.createEl("button", { text: "Apply" });
    applyButton.onclick = () => {
      this.code = codeInput.value.trim();
      const color = colorInput.value;
      if (this.code) {
        this.applyCodeToSelection(this.code, color);
      }
      this.close();
    };
  }
  applyCodeToSelection(code, color) {
    const selection = this.editor.getSelection();
    const codedText = `<span class="coded-text ${ApplyCodeModal.sanitizeCodeName(code)}" data-code="${code}">${selection}</span>`;
    this.editor.replaceSelection(codedText);
    ApplyCodeModal.saveCodeData(this.editor.getDoc().getValue());
    ApplyCodeModal.addDynamicStyle(code, color);
    ApplyCodeModal.storeStyle(code, color);
  }
  static saveCodeData(content) {
    var _a;
    const filePath = (_a = app.workspace.getActiveFile()) == null ? void 0 : _a.path;
    if (filePath) {
      const codeData = { path: filePath, content };
      localStorage.setItem("codeData", JSON.stringify(codeData));
    }
  }
  static addDynamicStyle(code, color) {
    const styleId = `style-${ApplyCodeModal.sanitizeCodeName(code)}`;
    let style = document.getElementById(styleId);
    if (!style) {
      style = document.createElement("style");
      style.id = styleId;
      document.head.appendChild(style);
    }
    style.innerHTML = `.coded-text.${ApplyCodeModal.sanitizeCodeName(code)} { background-color: ${color}; }`;
  }
  static storeStyle(code, color) {
    const styles = JSON.parse(localStorage.getItem("dynamicStyles") || "{}");
    styles[code] = color;
    localStorage.setItem("dynamicStyles", JSON.stringify(styles));
  }
  static sanitizeCodeName(code) {
    return code.replace(/[^a-z0-9]/gi, "-").toLowerCase();
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var RemoveCodeModal = class extends import_obsidian3.Modal {
  constructor(app2, editor) {
    super(app2);
    this.editor = editor;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: "Remove Code" });
    const removeButton = contentEl.createEl("button", { text: "Remove" });
    removeButton.onclick = () => {
      this.removeCodeFromSelection();
      this.close();
    };
  }
  removeCodeFromSelection() {
    const selection = this.editor.getSelection();
    const cleanedText = selection.replace(/<span\b[^>]*?\bclass="[^"]*\bcoded-text\b[^"]*"[^>]*?>([\s\S]*?)<\/span>/g, "$1");
    this.editor.replaceSelection(cleanedText);
    ApplyCodeModal.saveCodeData(this.editor.getDoc().getValue());
    this.removeDynamicStyle(cleanedText);
  }
  removeDynamicStyle(code) {
    const styleId = `style-${ApplyCodeModal.sanitizeCodeName(code)}`;
    const style = document.getElementById(styleId);
    if (style) {
      style.remove();
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
function cleanAllCodes(editor) {
  const content = editor.getValue();
  const cleanedContent = content.replace(/<span\b[^>]*?\bclass="[^"]*\bcoded-text\b[^"]*"[^>]*?>([\s\S]*?)<\/span>/g, "$1");
  editor.setValue(cleanedContent);
  localStorage.removeItem("dynamicStyles");
}
function getActiveEditor() {
  const activeLeaf = app.workspace.activeLeaf;
  if (activeLeaf) {
    const view = activeLeaf.view;
    if (view instanceof import_obsidian3.MarkdownView) {
      return view.editor;
    }
  }
  return null;
}
function loadCodeData() {
  var _a;
  const filePath = (_a = app.workspace.getActiveFile()) == null ? void 0 : _a.path;
  const codeData = localStorage.getItem("codeData");
  if (filePath && codeData) {
    const parsedCodeData = JSON.parse(codeData);
    if (parsedCodeData.path === filePath) {
      const activeFile = app.workspace.getActiveFile();
      if (activeFile) {
        app.vault.modify(activeFile, parsedCodeData.content);
      }
    }
  }
}
function reapplyStyles() {
  const styles = JSON.parse(localStorage.getItem("dynamicStyles") || "{}");
  for (const [code, color] of Object.entries(styles)) {
    ApplyCodeModal.addDynamicStyle(code, color);
  }
}

// src/customMenus.ts
var import_obsidian5 = require("obsidian");

// src/Highlights.ts
var import_obsidian4 = require("obsidian");
var Highlight = class extends import_obsidian4.Modal {
  constructor(app2, editor, selection) {
    super(app2);
    this.editor = editor;
    this.mySelection = selection;
  }
  onOpen() {
    this.apply("aa", "#FFCC00", this.mySelection);
  }
  apply(code, color, selection) {
    const codedText = `<span class="coded-text ${Highlight.sanitizeCodeName(code)}" data-code="${code}">${selection}</span>`;
    this.editor.replaceSelection(codedText);
    Highlight.addDynamicStyle(code, color);
  }
  remove(plugin, evt) {
    new import_obsidian4.Notice("AGORA");
    new import_obsidian4.Notice(this.mySelection);
    const mySelectionHTML = `<span class="coded-text aa" data-code="aa">${this.mySelection}</span>`;
    new import_obsidian4.Notice(mySelectionHTML);
    const regex = /<span class="coded-text aa" data-code="aa"[^>]*>([\s\S]*?)<\/span>/g;
    const selections = customMenus.removeHtmlTags(this.editor, regex, this.mySelection, mySelectionHTML, evt);
    if (plugin.codingMenuOpened) {
      console.log("CODING ABERTO");
    } else {
      console.log("CODING NAO ABERTO");
    }
  }
  static sanitizeCodeName(code) {
    return code.replace(/[^a-z0-9]/gi, "-").toLowerCase();
  }
  static addDynamicStyle(code, color) {
    const styleId = `style-${Highlight.sanitizeCodeName(code)}`;
    let style = document.getElementById(styleId);
    if (!style) {
      style = document.createElement("style");
      style.id = styleId;
      document.head.appendChild(style);
    }
    style.innerHTML = `.coded-text.${Highlight.sanitizeCodeName(code)} { background-color: ${color}; }`;
  }
  removeDynamicStyle(code) {
    const styleId = `style-${Highlight.sanitizeCodeName(code)}`;
    const style = document.getElementById(styleId);
    if (style) {
      style.remove();
    }
  }
  static saveCodeData(content) {
    var _a;
    const filePath = (_a = app.workspace.getActiveFile()) == null ? void 0 : _a.path;
    if (filePath) {
      const codeData = { path: filePath, content };
      localStorage.setItem("codeData", JSON.stringify(codeData));
    }
  }
};

// src/customMenus.ts
var _customMenus = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  static async showCustomMenu(evt, plugin) {
    var _a;
    const view = plugin.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (!view)
      return;
    const editor = view.editor;
    if (!editor.hasFocus())
      return;
    if (evt.type === "mouseover") {
      new import_obsidian5.Notice("Mouseover event detected");
      await this.createEditorCodingMenu(editor, evt, plugin);
      return;
    }
    const selectedText = editor.getSelection();
    if (!selectedText) {
      this.cleanupCallbacks.forEach((callback) => callback());
      return;
    }
    if (!plugin.codingMenuOpened && !plugin.menuStayOpen) {
      if (plugin.currentMenu) {
        await this.resetMenu(plugin);
      }
      const editor2 = (_a = app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView)) == null ? void 0 : _a.editor;
      if (editor) {
        console.log("FOIIIII");
      }
      await this.createEditorCodingMenu(editor, evt, plugin);
      return;
    }
  }
  // Converte um índice em uma posição de linha e coluna
  static indexToPos(editor, index) {
    const content = editor.getValue();
    const lines = content.split("\n");
    let currentPos = 0;
    for (let line = 0; line < lines.length; line++) {
      const lineLength = lines[line].length + 1;
      if (index < currentPos + lineLength) {
        return { line, ch: index - currentPos };
      }
      currentPos += lineLength;
    }
    return { line: lines.length - 1, ch: lines[lines.length - 1].length };
  }
  static posToIndex(editor, pos) {
    const content = editor.getValue();
    const lines = content.split("\n");
    let index = 0;
    for (let line = 0; line < pos.line; line++) {
      index += lines[line].length + 1;
    }
    return index + pos.ch;
  }
  static getCursorPosition(editor) {
    const start = editor.getCursor("from");
    const end = editor.getCursor("to");
    return { start, end };
  }
  /* static getClickPosition(event: MouseEvent, editor: Editor): EditorPosition {
          const cm = (editor as any).cm;
          const coords = { line: event.clientX, ch: event.clientY };
          //const pos = cm.coordsChar(coords, "window");
          //return { line: pos.line, ch: pos.ch };
          //const newPos = this.posToIndex(editor,coords);
  
          //return {line: newPos, ch: newPos};
      } */
  /* static initializeClickEvent(editor: Editor) {
      document.addEventListener('mousedown', (event: MouseEvent) => {
          console.log("UNO")
          //if ((event.target as HTMLElement).closest('.CodeMirror')) {
              console.log("DOES")
              //const clickPosition = customMenus.getClickPosition(event, editor);
              //console.log("Click Position:", clickPosition); // Para verificar a posição capturada
              //customMenus.lastClickPosition = clickPosition; // Armazena a posição do clique
         // }
      });
  } */
  static setCursorToLastClickPosition(editor) {
    if (_customMenus.lastClickPosition) {
      editor.setCursor(_customMenus.lastClickPosition);
      editor.focus();
    }
  }
  static setCursorSelection(editor, start, end) {
    editor.setSelections([{ anchor: start, head: end }]);
  }
  // Nova função para definir o cursor em uma posição específica
  static setCursorPosition(editor, position) {
    editor.setCursor(position);
  }
  static async removeHtmlTags(editor, regex, originText, mySelectionHTML, evt) {
    let content = editor.getValue();
    let match;
    const selections = [];
    let offset = 0;
    const openingTagLength = `<span class="coded-text aa" data-code="aa">`.length;
    const closingTagLength = `</span>`.length;
    const total = openingTagLength + closingTagLength;
    while ((match = regex.exec(content)) !== null) {
      const innerContent = match[1];
      const startIndex = match.index;
      new import_obsidian5.Notice(`${startIndex}`);
      console.log("startIndex");
      console.log(startIndex);
      const endIndex = startIndex + match[0].length + total;
      new import_obsidian5.Notice(`> ${endIndex}`);
      offset += innerContent.length - match[0].length;
      const startPos = this.indexToPos(editor, startIndex);
      const endPos = this.indexToPos(editor, endIndex);
      selections.push({ anchor: startPos, head: endPos });
      console.log("selections");
      console.log(selections);
    }
    if (selections.length > 0) {
      const selectionStartIndex = this.posToIndex(editor, selections[0].anchor);
      const selectionEndIndex = selectionStartIndex + originText.length + openingTagLength + closingTagLength;
      console.log("selectionStartIndex");
      console.log(selectionStartIndex);
      const startPos = this.indexToPos(editor, selectionStartIndex);
      const endPos = this.indexToPos(editor, selectionEndIndex);
      const cursorPosition = this.getCursorPosition(editor);
      const cursorIndex = this.posToIndex(editor, cursorPosition.start);
      const cursorFinal = this.indexToPos(editor, cursorIndex);
      if (endPos.line < cursorFinal.line) {
        console.log("Clicou ABAIXO do texto selecionado");
        _customMenus.setCursorSelection(editor, startPos, endPos);
        editor.replaceSelection(originText);
        _customMenus.setCursorPosition(editor, cursorFinal);
      } else if (endPos.line > cursorFinal.line) {
        console.log("Clicou ACIMA do texto selecionado");
        _customMenus.setCursorSelection(editor, startPos, endPos);
        editor.replaceSelection(originText);
        _customMenus.setCursorPosition(editor, cursorFinal);
      } else if (endPos.line === cursorFinal.line) {
        console.log("Mesma linha");
        if (endPos.ch < cursorFinal.ch) {
          console.log("DEPOIS da sele\xE7\xE3o");
          _customMenus.setCursorSelection(editor, startPos, endPos);
          editor.replaceSelection(originText);
          const point = cursorIndex - total;
          const newCursorPosition = this.indexToPos(editor, point);
          this.setCursorPosition(editor, newCursorPosition);
        } else if (endPos.ch > cursorFinal.ch) {
          _customMenus.setCursorSelection(editor, startPos, endPos);
          editor.replaceSelection(originText);
          _customMenus.setCursorPosition(editor, cursorFinal);
          console.log("ANTES da sele\xE7\xE3o");
        } else {
          if (!editor.hasFocus) {
            console.log("SEM FOCO");
          } else {
            console.log("SAIU");
          }
          console.log("No meio do TEXTO.");
          console.log(endPos);
          console.log(endPos.ch - total);
          console.log(cursorFinal.ch);
          this.setCursorSelection(editor, startPos, endPos);
          editor.replaceSelection(originText);
          const lineNumber = startPos.line;
          const line = editor.getLine(lineNumber);
          const position = line.indexOf(originText);
          console.log("position: " + position);
          endPos.ch = endPos.ch - total;
          this.setCursorSelection(editor, startPos, endPos);
          console.log(editor.getSelection());
        }
      }
      return selections;
      if (endPos.line > cursorFinal.line || endPos.line === cursorFinal.line && endPos.ch > cursorFinal.ch) {
        console.log("situa\xE7\xE3o 1");
        console.log("startPos");
        console.log(startPos.ch);
        console.log(startPos.line);
        console.log("---");
        console.log("endPos");
        console.log(endPos.ch);
        console.log(endPos.line);
        console.log("---");
        console.log("cursorFinal");
        console.log(cursorFinal.ch);
        console.log(cursorFinal.line);
        console.log("-----------------------");
      } else {
        console.log("startPos");
        console.log(startPos.ch);
        console.log(startPos.line);
        console.log("---");
        console.log("endPos");
        console.log(endPos.ch);
        console.log(endPos.line);
        console.log("---");
        console.log("cursorFinal");
        console.log(cursorFinal.ch);
        console.log(cursorFinal.line);
        console.log("-----------------------");
      }
      if (startPos.line > cursorFinal.line || startPos.line === cursorFinal.line && endPos.ch > cursorFinal.ch) {
        console.log("situa\xE7\xE3o 2");
        console.log("startPos");
        console.log(startPos.ch);
        console.log(startPos.line);
        console.log("---");
        console.log("endPos");
        console.log(endPos.ch);
        console.log(endPos.line);
        console.log("---");
        console.log("cursorFinal");
        console.log(cursorFinal.ch);
        console.log(cursorFinal.line);
        console.log("-----------------------");
      } else {
        console.log("situa\xE7\xE3o 4");
        console.log("startPos");
        console.log(startPos.ch);
        console.log(startPos.line);
        console.log("---");
        console.log("endPos");
        console.log(endPos.ch);
        console.log(endPos.line);
        console.log("---");
        console.log("cursorFinal");
        console.log(cursorFinal.ch);
        console.log(cursorFinal.line);
        console.log("-----------------------");
      }
    }
  }
  static async createEditorCodingMenu(editor, evt, plugin) {
    const submenu = new import_obsidian5.Menu();
    const selectedText = editor.getSelection();
    const cursorPosition = this.getCursorPosition(editor);
    let mark = new Highlight(app, editor, selectedText);
    plugin.myCustomMenu.forEach((option, index) => {
      if (option.isToggle) {
        submenu.addItem((item) => {
          var _a;
          const toggleComponent = new import_obsidian5.ToggleComponent(item.dom);
          toggleComponent.setValue((_a = option.isEnabled) != null ? _a : false);
          toggleComponent.onChange((value) => {
            option.isEnabled = value;
            option.action(plugin);
          });
          item.setTitle(option.title).setIcon(option.icon);
          item.dom.classList.add("menu-item-toggle");
          item.dom.addEventListener("click", (evt2) => {
            evt2.stopPropagation();
            const currentValue = toggleComponent.getValue();
            toggleComponent.setValue(!currentValue);
          });
        });
        if (index === 1 + (plugin.menuCodesReduced.length - 1)) {
          submenu.addSeparator();
        }
      } else if (option.isTextField) {
        submenu.addItem((item) => {
          const textComponent = new import_obsidian5.TextComponent(item.dom);
          textComponent.setPlaceholder("Enter text...");
          textComponent.onChange((value) => {
            option.action(plugin);
          });
          item.setTitle(option.title).setIcon(option.icon);
          item.dom.classList.add("menu-item-textfield");
          item.dom.addEventListener("click", (evt2) => {
            evt2.stopPropagation();
            evt2.preventDefault();
            textComponent.inputEl.focus();
          });
          const handleEnterKey = (evt2) => {
            if (evt2.key === "Enter") {
              evt2.stopPropagation();
              evt2.preventDefault();
              if (this.lastMouseEvent) {
                this.cleanupCallbacks.forEach((callback) => callback());
                this.addItemToEditorCodingMenu(textComponent.inputEl.value, plugin, editor, submenu, this.lastMouseEvent);
              }
            }
          };
          this.cleanupCallbacks.push(() => {
            window.removeEventListener("keydown", handleEnterKey, true);
          });
          this.focusCallbacks.push(() => {
            textComponent.inputEl.focus();
            if (!plugin.menuStayOpen) {
              mark.onOpen();
            }
          });
          window.addEventListener("keydown", handleEnterKey, true);
        });
      } else {
        submenu.addItem((item) => {
          item.setTitle(option.title).setIcon(option.icon).onClick(() => {
            option.action(plugin);
            this.resetMenu(plugin);
          });
        });
      }
    });
    submenu.onHide(async () => {
      plugin.codingMenuOpened = false;
      plugin.menuStayOpen = true;
      this.resetMenu(plugin);
      mark.remove(plugin, evt);
    });
    plugin.codingMenuOpened = true;
    submenu.showAtPosition({ x: evt.pageX, y: evt.pageY });
    this.focusCallbacks.forEach((callback) => callback());
    this.focusCallbacks = [];
    this.lastMouseEvent = evt;
    plugin.currentMenu = submenu;
  }
  static addItemToEditorCodingMenu(value, plugin, editor, submenu, originalEvent) {
    if (value.trim() !== "") {
      const newOption = {
        title: value,
        icon: "tag",
        action: (plugin2) => {
          new import_obsidian5.Notice(`Toggle ${value} executed`);
        },
        isToggle: true,
        isEnabled: true
      };
      plugin.menuCodes.unshift(newOption);
      submenu.hide();
      this.createEditorCodingMenu(editor, originalEvent, plugin);
      plugin.codingMenuOpened = true;
    }
  }
  static async resetMenu(plugin, hideMenu = true) {
    if (plugin.currentMenu) {
      plugin.currentMenu.hide();
      this.destroyMenu(plugin.currentMenu);
      plugin.currentMenu = null;
    }
    plugin.codingMenuOpened = false;
    plugin.menuStayOpen = false;
  }
  static destroyMenu(menu) {
    if (menu && menu.dom) {
      const menuDom = menu.dom;
      if (menuDom.parentNode) {
        menuDom.parentNode.removeChild(menuDom);
      }
    }
  }
};
var customMenus = _customMenus;
//static app: any;
customMenus.handleEnterKey = null;
customMenus.lastMouseEvent = null;
customMenus.cleanupCallbacks = [];
customMenus.focusCallbacks = [];
customMenus.lastClickPosition = null;

// src/Events.ts
var EventManager = class {
  constructor(plugin) {
    this.plugin = plugin;
  }
  registerEvents() {
    this.customMenuEventsManagement(this.plugin);
    this.codingEventsManagement(this.plugin);
  }
  customMenuEventsManagement(plugin) {
    this.plugin.registerDomEvent(document, "click", async (evt) => {
      await customMenus.showCustomMenu(evt, plugin);
      const markdownView = plugin.app.workspace.getActiveViewOfType(import_obsidian6.MarkdownView);
      if (!markdownView)
        return;
      console.log("click", evt);
      const editor = markdownView.editor;
      const start = editor.getCursor("from");
      const end = editor.getCursor("to");
      const cursor = editor.getCursor();
      console.log("start", start);
      console.log("end", end);
      const cmEditor = editor.cm;
      if (cmEditor) {
        console.log(cmEditor.getLine);
        console.log(cmEditor.hasFocus);
        if (!cmEditor.hasFocus) {
          console.log("SAIU do FOCO!!!");
          console.log(editor.getCursor());
          evt.stopPropagation();
          evt.preventDefault();
          console.log(editor.getCursor());
          console.log(cmEditor);
        } else {
          console.log("VOLTOU para FOCO?");
        }
      }
    });
  }
  codingEventsManagement(plugin) {
    plugin.registerEvent(plugin.app.workspace.on("file-open", () => {
      loadCodeData();
      reapplyStyles();
    }));
    plugin.registerDomEvent(document, "DOMContentLoaded", () => {
      const link = document.createElement("link");
      link.rel = "stylesheet";
      link.href = "styles.css";
      document.head.appendChild(link);
      reapplyStyles();
    });
  }
};

// src/Codings.ts
var import_obsidian7 = require("obsidian");
function addNewCode(plugin) {
  const editor = getActiveEditor();
  if (editor) {
    new ApplyCodeModal(plugin.app, editor).open();
  }
  CodingMenuManager.resetMenu(this);
}
function addExistingCode(plugin) {
  new import_obsidian7.Notice("Add Existing Code");
  CodingMenuManager.resetMenu(this);
}
function removeCode(plugin) {
  const editor = getActiveEditor();
  if (editor) {
    new RemoveCodeModal(plugin.app, editor).open();
  }
  CodingMenuManager.resetMenu(this);
}
function removeAllCodes(plugin) {
  const editor = getActiveEditor();
  if (editor) {
    cleanAllCodes(editor);
  }
  CodingMenuManager.resetMenu(this);
}

// main.ts
var MyPlugin = class extends import_obsidian8.Plugin {
  constructor() {
    super(...arguments);
    this.currentMenu = null;
    this.menuInput = [
      { title: "", icon: "tag", action: (plugin) => {
      }, isTextField: true }
    ];
    this.menuCodes = [];
    this.menuOptions = [
      //{ title: 'Toggle Example', icon: 'switch', action: (plugin) => toggleExample(plugin), isToggle: true, isEnabled: false },
      { title: "Add New Code", icon: "plus-with-circle", action: (plugin) => addNewCode(plugin) },
      { title: "Add Existing Code", icon: "tag", action: (plugin) => addExistingCode(plugin) },
      { title: "Remove Code", icon: "trash", action: (plugin) => removeCode(plugin) },
      { title: "Remove All Codes", icon: "minus-with-circle", action: (plugin) => removeAllCodes(plugin) }
    ];
    // Definindo propriedades faltantes
    this.contextMenuOpened = false;
    this.selectionTriggeredMenu = false;
    this.codingMenuOpened = false;
    this.menuStayOpen = false;
  }
  get menuCodesReduced() {
    return this.menuCodes.slice(0, 5);
  }
  get myCustomMenu() {
    return [
      ...this.menuInput,
      ...this.menuCodesReduced,
      ...this.menuOptions
    ];
  }
  async onload() {
    console.log("[Marlon QDA] v10 loaded -- MQDA: MenuOption, CodingMenuManager, EventManager, FindAndReplace");
    this.stdMenuManager = new StandardMenus(this);
    this.eventManager = new EventManager(this);
    this.stdMenuManager.createMenus();
    this.eventManager.registerEvents();
    new import_obsidian8.Notice("MOSx-QDA loaded!!");
  }
  onunload() {
    CodingMenuManager.cleanupCallbacks.forEach((callback) => callback());
    new import_obsidian8.Notice("MOSx-QDA unloaded!");
  }
  onEditorChange(editor) {
    const codedTextElements = document.querySelectorAll(".coded-text");
    codedTextElements.forEach((span) => {
      this.addHoverListeners(span);
      console.log(span);
    });
  }
  addHoverListeners(span) {
    if (!span.classList.contains("hover-listeners-added")) {
      span.addEventListener("mouseover", (event) => {
        customMenus.showCustomMenu(event, this);
      });
      span.addEventListener("mouseout", () => {
      });
      span.classList.add("hover-listeners-added");
    }
  }
};
